# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read # for actions/checkout to fetch code
      security-events: write # for GitHub/codeql-action/upload-sarif to upload SARIF results

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Checkov GitHub Action
        # You may pin to the exact commit or the version.
        # uses: bridgecrewio/checkov-action@99bb2caf247dfd9f03cf984373bc6043d4e32ebf
        uses: bridgecrewio/checkov-action@master
        with:
          #soft_fail: true
          api-key: ${{ secrets.BC_API_KEY }}
          external_checks_dirs: "${{ github.workspace }}/checkov_custom_checks"
          use_enforcement_rules: true
          # directory with infrastructure code to scan
          #directory: # optional, default is .
          # Run scan only on a specific check identifier (comma separated)
          #check: # optional
          # Run scan on all checks but a specific check identifier (comma separated)
          #skip_check: # optional
          # display only failed checks
          #quiet: # optional
          # Environment variable name of the Bridgecrew API key from Bridgecrew app
          #api-key: # optional
          # do not return an error code if there are failed checks
          #soft_fail: # optional
          # run only on a specific infrastructure
          framework: sca_package
          # comma separated list of external (custom) checks directories
          #external_checks_dirs: # optional
          # comma separated list of external (custom) checks repositories
          #external_checks_repos: # optional
          # The format of the output. cli, json, junitxml, github_failed_only, or sarif
          #output_format: # optional, default is sarif
          # download external terraform modules from public git repositories and terraform registry:true, false
          download_external_modules: true # optional
        env:
          PRISMA_API_URL: https://api2.prismacloud.io

      - name: Upload SARIF file
        uses: GitHub/codeql-action/upload-sarif@v3
      
        # Results are generated only on a success or failure
        # this is required since GitHub by default won't run the next step
        # when the previous one has failed. Alternatively, enable soft_fail in checkov action.
        if: success() || failure()
        with:
          sarif_file: results.sarif

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
